### PR TITLE
fix: resolve toast notification display issue

### LINKED ISSUE #4: Minor frontend improvements
### Objective
A toast can be shown while logging out. Code managing default values while filling out the register form can be improved.

### Learning
- You will learn some concepts used in react-hook-form and react-hot-toast

### Guidelines
- Currently, register form is using useEffect hook to fill in default values. It must be changed to the proper method given in docs of react-hook-form
- Toast must be added while the student or professor is logging out

### PR DESCRIPTION
**Pull request by AritraDey-Dev**
fixes #4 
This pull request includes several changes to improve user experience and streamline the codebase. The most important changes include updating environment variables, enhancing the logout functionality with notifications, and refactoring the `RegisterForm` component to use default values directly.

### Environment Variables Update:
* [`.env.example`](diffhunk://#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8cL1-R6): Updated the `DB_CONNECTION_STRING` and added values for `AUTH_CLIENT_SECRET`, `AUTH_CLIENT_ID`, `NEXTAUTH_URL`, and `NEXTAUTH_SECRET`.

### Logout Functionality Enhancement:
* [`src/app/professor/home/_components/Buttons.tsx`](diffhunk://#diff-c799098e6381ec90773fde1bf54328b7dbc21a74ede6ec7bfbe3552f9321b962R6): Added toast notifications for loading and success states during the logout process. [[1]](diffhunk://#diff-c799098e6381ec90773fde1bf54328b7dbc21a74ede6ec7bfbe3552f9321b962R6) [[2]](diffhunk://#diff-c799098e6381ec90773fde1bf54328b7dbc21a74ede6ec7bfbe3552f9321b962L16-R20)
* [`src/app/student/home/_components/Buttons.tsx`](diffhunk://#diff-0ce7a4e50f32cb588c704c409d7033fb301ef763dac7fb9b10066917eb4a866eR6): Added toast notifications for loading and success states during the logout process. [[1]](diffhunk://#diff-0ce7a4e50f32cb588c704c409d7033fb301ef763dac7fb9b10066917eb4a866eR6) [[2]](diffhunk://#diff-0ce7a4e50f32cb588c704c409d7033fb301ef763dac7fb9b10066917eb4a866eL16-R20)

### Codebase Simplification:
* [`src/app/register/_components/RegisterForm.tsx`](diffhunk://#diff-226e10c9a79d2ddc065ab233a58202f6c9496a8f3ba3a5b90d25dca09d7daf1bL11): Removed the `useEffect` hook and set default values directly in the form initialization. [[1]](diffhunk://#diff-226e10c9a79d2ddc065ab233a58202f6c9496a8f3ba3a5b90d25dca09d7daf1bL11) [[2]](diffhunk://#diff-226e10c9a79d2ddc065ab233a58202f6c9496a8f3ba3a5b90d25dca09d7daf1bR24-R28) [[3]](diffhunk://#diff-226e10c9a79d2ddc065ab233a58202f6c9496a8f3ba3a5b90d25dca09d7daf1bL40-L45)

### CODE REVIEW

File: src/app/professor/home/_components/Buttons.tsx
Comment (Arjun-G-04) [inline src/app/professor/home/_components/Buttons.tsx:1]: in CustomButton.tsx, there is a provision for using async function. so please make use of it as signOut is also async

**Review by Arjun-G-04 — CHANGES_REQUESTED** [review]

File: src/app/professor/home/_components/Buttons.tsx
Comment (AritraDey-Dev) [reply src/app/professor/home/_components/Buttons.tsx:1]: @Arjun-G-04 i hope this commit (https://github.com/Arjun-G-04/classnitte/pull/7/commits/e59c0a62699370ccf178abf6bc5583be3717eb47) fix the required issue.Can you please check and tell any changes required.

**Comment by AritraDey-Dev** [comment]
@Arjun-G-04 can you review the pr and inform me if it works for the codebase

**Comment by Arjun-G-04** [comment]
> @Arjun-G-04 can you review the pr and inform me if it works for the codebase

hey I think you can make use of the async type in CustomButton rather than the sync type

File: src/app/student/home/_components/Buttons.tsx [hunk 1]
```diff
@@ -3,19 +3,24 @@
...
 	return (
 		<div className="flex flex-row gap-5">
-			<CustomButton
-				type="sync"
-				text="Logout"
-				syncFn={() => {
-					signOut();
-				}}
-			/>
+			<CustomButton type="sync" text="Logout" syncFn={handleLogout} />
```
Comment (Arjun-G-04) [inline src/app/student/home/_components/Buttons.tsx]: use type="async"

**Review by Arjun-G-04 — CHANGES_REQUESTED** [review]

**Comment by AritraDey-Dev** [comment]
Screenshot from 2025-02-06 16-54-50
I have added the async functionality.
@Arjun-G-04 Can you please check and inform if any changes required.

**Comment by AritraDey-Dev** [comment]
@Arjun-G-04 any changes you need for this pr?

**Comment by AritraDey-Dev** [comment]
Is this repo even active for dwoc?

**Comment by Arjun-G-04** [comment]
Hello! sorry for the late review, was caught up with other things in the past few weeks

File: src/app/professor/home/_components/Buttons.tsx [hunk 2]
```diff
@@ -3,18 +3,28 @@
...
 
 	return (
 		<div className="flex flex-row gap-5">
 			<CustomButton
-				type="sync"
+				type="async"
 				text="Logout"
-				syncFn={() => {
-					signOut();
+				asyncFn={async () => {
```
Comment (Arjun-G-04) [inline src/app/professor/home/_components/Buttons.tsx:15]: you are in the right track. There is no necessity for making an error toast once again here. The CustomButton automatically takes care of that. So that can be removed. Plus, look into what the "loading" prop actually does and why the value "true" may not be relevant. Also make sure biome and pre-commit hooks are running since the code appears to be not formatted.

**Review by Arjun-G-04 — CHANGES_REQUESTED** [review]

File: src/app/professor/home/_components/Buttons.tsx (hunk 2 above)
Comment (AritraDey-Dev) [reply src/app/professor/home/_components/Buttons.tsx:15]: yes there is no use of that toast and i have fixed the loading props too.Please have a look on that.Now while loading it will be "logging out..." and then it will be "logged out successfully". Hope this helps.

**Comment by Arjun-G-04** [comment]
@AritraDey-Dev the code logic looks good, can you make sure to format the code once using biome.js and push?

**Comment by AritraDey-Dev** [comment]
> @AritraDey-Dev the code logic looks good, can you make sure to format the code once using biome.js and push?

I have run `npm run format` to format the code.So it's already formatted.And after formatting I have committed the changes.

**Comment by Arjun-G-04** [comment]
alright cool, I will check it out.

**Review by Arjun-G-04 — APPROVED** [review]
lgtm

**Comment by Arjun-G-04** [comment]
@AritraDey-Dev your changes looks good to me! I am merging this PR now. If you are interested in contributing further, let me know, I will plan more complex features.
